#!/usr/bin/env python3
"""Generate Unicode 16 text segmentation tables; no runtime platform ICU dependency."""
import argparse
import hashlib
import json
from pathlib import Path
import urllib.request

ROOT = Path(__file__).resolve().parent.parent
FILES = {
    'GraphemeBreakTest.txt': ('auxiliary/GraphemeBreakTest.txt', 'ee2b9354d270ac061b29f09662cafea06341d77e704b8cc6bd72aaeeda363cb5'),
    'GraphemeBreakProperty.txt': ('auxiliary/GraphemeBreakProperty.txt', 'c29360bd6f7132811d701d29069541e827eb44bfc4c8fbde8c370d6982689dc1'),
    'DerivedCoreProperties.txt': ('DerivedCoreProperties.txt', '39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd'),
    'emoji-data.txt': ('emoji/emoji-data.txt', 'f1365a5173eee18e1f98b240cdc492e84a25f1ce7e0c9d1094eb29c41a22696a'),
}
KINDS = {'Control': 1, 'CR': 2, 'LF': 3, 'Extend': 4, 'ZWJ': 5, 'Regional_Indicator': 6,
         'Prepend': 7, 'SpacingMark': 8, 'L': 9, 'V': 10, 'T': 11, 'LV': 12, 'LVT': 13}
parser = argparse.ArgumentParser()
parser.add_argument('--cache', type=Path, required=True, help='Directory for hash-verified Unicode source files')
args = parser.parse_args()
args.cache.mkdir(parents=True, exist_ok=True)
data = {}
for name, (path, digest) in FILES.items():
    file = args.cache / name
    if not file.exists():
        file.write_bytes(urllib.request.urlopen('https://www.unicode.org/Public/16.0.0/ucd/' + path).read())
    raw = file.read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        raise SystemExit(f'Unicode source hash mismatch: {file}')
    data[name] = raw

properties = [0] * 0x110000
for name in ['GraphemeBreakProperty.txt', 'DerivedCoreProperties.txt', 'emoji-data.txt']:
    for line in data[name].decode().splitlines():
        fields = [part.strip() for part in line.split('#')[0].split(';')]
        if len(fields) < 2:
            continue
        if name == 'GraphemeBreakProperty.txt':
            if fields[1] in ['LV', 'LVT']:
                continue  # Hangul syllables use their arithmetic definition.
            value = KINDS[fields[1]]
        elif name == 'DerivedCoreProperties.txt':
            if fields[1] != 'InCB':
                continue
            value = {'Consonant': 16, 'Extend': 32, 'Linker': 48}[fields[2]]
        else:
            if fields[1] != 'Extended_Pictographic':
                continue
            value = 64
        bounds = fields[0].split('..')
        start, end = int(bounds[0], 16), int(bounds[-1], 16)
        for codepoint in range(start, end + 1):
            properties[codepoint] |= value

ranges = []
start = 0
for end in range(1, len(properties) + 1):
    if end == len(properties) or properties[end] != properties[start]:
        if properties[start]:
            ranges.append((start, end - 1, properties[start]))
        start = end
fixture = ROOT / 'fixtures/unicode/grapheme-properties-16.0.0.json'
fixture.write_text(json.dumps({'unicodeVersion': '16.0.0', 'ranges': ranges}, separators=(',', ':')) + '\n')
(ROOT / 'fixtures/unicode/GraphemeBreakTest-16.0.0.txt').write_bytes(data['GraphemeBreakTest.txt'])
output = ROOT / 'Sources/Nuxie/Experiences/UnicodeGraphemeProperties.swift'
lines = ['// Generated by scripts/generate-text-input-unicode.py from Unicode 16.0.0.',
         '// Unicode data license: Sources/Nuxie/Resources/LICENSE-unicode.txt.',
         'enum UnicodeGraphemeProperties {',
         '    static func get(_ codepoint: Int) -> Int {',
         '        if (0xAC00...0xD7A3).contains(codepoint) {',
         '            return (codepoint - 0xAC00) % 28 == 0 ? 12 : 13',
         '        }',
         '        var low = 0', '        var high = ranges.count / 3 - 1',
         '        while low <= high {', '            let mid = (low + high) / 2',
         '            let offset = mid * 3',
         '            if codepoint < ranges[offset] { high = mid - 1 }',
         '            else if codepoint > ranges[offset + 1] { low = mid + 1 }',
         '            else { return ranges[offset + 2] }',
         '        }', '        return 0', '    }', '',
         '    private static let ranges: [Int] = [']
lines.extend(f'        0x{start:X}, 0x{end:X}, {value},' for start, end, value in ranges)
lines.extend(['    ]', '}', ''])
output.write_text('\n'.join(lines))
print(f'Generated {len(ranges)} Unicode 16.0.0 property ranges and shared data')
