"""Two focusable nodes with listeners on separate state machines."""
from pathlib import Path
import hashlib
import json
import struct


def uint(value):
    output = bytearray()
    while value >= 128:
        output.append((value & 127) | 128)
        value >>= 7
    output.append(value)
    return bytes(output)


def number(key, value):
    return uint(key) + uint(value)


def string(key, value):
    data = value.encode("utf-8")
    return uint(key) + uint(len(data)) + data


def object_bytes(kind, *properties):
    return uint(kind) + b"".join(properties) + b"\0"


# Type/property keys come from runtime 79ea46919 defs/upstream-runtime.
# The object shape follows its tests/support/focus_input.rs key_moves_focus.
data = b"RIVE" + b"".join(uint(value) for value in [7, 0, 9658, 0])
data += object_bytes(23)
data += object_bytes(1, string(4, "Composite"),
                     uint(7) + struct.pack("<f", 100),
                     uint(8) + struct.pack("<f", 100), number(236, 0))
for _ in range(2):
    data += object_bytes(2, number(5, 0))
for parent in [1, 2]:
    data += object_bytes(653, number(5, parent), number(1033, 7))
for name in ["first_focused", "second_focused"]:
    data += object_bytes(128, string(4, name))
for machine, node, event in [("Primary", 1, 5), ("Auxiliary", 2, 6)]:
    data += object_bytes(53, string(55, machine))
    data += object_bytes(114, number(224, node), number(225, 13))
    data += object_bytes(168, number(389, event))

root = Path(__file__).resolve().parent
(root / "screen.riv").write_bytes(data)
(root / "provenance.json").write_text(json.dumps({
    "sourceRepository": "https://github.com/nuxieai/nuxie-runtime",
    "sourceCommit": "79ea4691971958501c64f7ff55076790ec8c9c4d",
    "sourcePath": "crates/nuxie-runtime/tests/support/focus_input.rs",
    "authorship": "SDK-authored two-machine variant of key_moves_focus; generated by generate.py.",
    "sha256": hashlib.sha256(data).hexdigest(),
    "expected": {"next": ["first_focused"], "nextAgain": ["second_focused"],
                 "previous": ["first_focused"]}
}, indent=2) + "\n")
