import RiveRuntime
import XCTest

@testable import Nuxie

/// End-to-end coverage for device-side script execution: a real `.riv`
/// carrying an embedded Luau module that calls `Nuxie.response.set(...)`
/// imports through the fork runtime with the Nuxie script bridge attached,
/// and the call must surface as a drained `$response_set` renderer event.
///
/// The fixture is generated by the monorepo's rive-compiler:
/// `rive-compiler-cli emit-scripted-riv` wrapping Luau bytecode for
///
///     local Nuxie = require("nuxie")
///     Nuxie.response.set("plan", "pro")
///     return {}
///
/// compiled with the same Luau revision the Rive runtime embeds. The script
/// is intentionally unsigned, so registering it requires the explicit
/// `allowsUnverifiedScripts` opt-in on `RiveScriptRuntime`.
final class NuxieRiveScriptBridgeScriptExecutionTests: XCTestCase {
    private func fixtureData() throws -> Data {
        let bundle = Bundle(for: Self.self)
        let url = bundle.url(
            forResource: "scripted_response_set",
            withExtension: "riv",
            subdirectory: "Fixtures"
        ) ?? bundle.url(forResource: "scripted_response_set", withExtension: "riv")
        return try Data(contentsOf: XCTUnwrap(url))
    }

    func testScriptedRivResolvesNuxieResponseSetThroughNestedModuleTables() throws {
        let bridge = NuxieRiveScriptBridge()
        bridge.scriptRuntime.allowsUnverifiedScripts = true

        _ = try RiveFile(
            data: fixtureData(),
            loadCdn: false,
            scriptRuntime: bridge.scriptRuntime
        )

        let events = bridge.drainEvents(currentScreenId: "screen_1")
        XCTAssertEqual(events.count, 1)
        let event = try XCTUnwrap(events.first)
        XCTAssertEqual(event.name, SystemEventNames.responseSet)
        XCTAssertEqual(event.properties["field"] as? String, "plan")
        XCTAssertEqual(event.properties["value"] as? String, "pro")
        XCTAssertEqual(event.screenId, "screen_1")
    }

    func testScriptedRivWithoutOptInDrainsNoEvents() throws {
        let bridge = NuxieRiveScriptBridge()
        // allowsUnverifiedScripts stays NO: the unsigned module must not
        // register, so the script never runs and nothing drains.

        _ = try RiveFile(
            data: fixtureData(),
            loadCdn: false,
            scriptRuntime: bridge.scriptRuntime
        )

        XCTAssertTrue(bridge.drainEvents(currentScreenId: "screen_1").isEmpty)
    }
}
